### ISSUE TITLE
String convert?

### ISSUE THREAD

**Issue by chraibi** [bsmoehring/jpsTools#21]
I have a question to this [line](https://github.com/bsmoehring/jpsTools/blob/master/jpsTools/osmImport/handler.py#L263), 
which gives me a `SyntaxError: invalid syntax`

Do you mean to convert `i` to a str? (`str(i)`)

**Comment by bsmoehring** [comment]
it works for me the way i did it. but yes, i do save all id's as strings. 
does it work if you do str(i) ?

**Comment by chraibi** [comment]
yes `str(i)` works. 
Maybe the operator you are using is  python2 specific.
