### ISSUE TITLE
no attribute 'iteritems'

### ISSUE THREAD

**Issue by chraibi** [bsmoehring/jpsTools#22]
Running 
```
python main.py
```
gives the following error

<img width="980" alt="screen shot 2018-01-19 at 12 16 22" src="https://user-images.githubusercontent.com/5772973/35148494-af539cee-fd12-11e7-8055-be226c1fcc63.png">

**Comment by bsmoehring** [comment]
interesting. I can't reproduce the error and I don't see why not iteritems() shouldn't work for a dictionary. 

Does your variable self.nodes look like this when debugging?
dict: {'1587310395': <Element 'node' at 0x7ffe550>, '1587310390': <Element 'node' at 0x7ffe3f0>,  .......

**Comment by bsmoehring** [comment]
I found it. 
dic.iteritems() was changed to dic.items() in python3. 
When I started the project it was recommended to use the shapely library, which is the key library of my project, with python2. It seems that it has been tested with python3 now. I will update to python3 and adapt the code. Gonna let you know as soon as I'm done with this

**Comment by chraibi** [comment]
I've installed all packages with `pip3`. So if there is no special reason for sticking with python2, I would suggest to switch to python3. 

I did already some changes in this regard. I'll make a PR soon.

**Comment by bsmoehring** [comment]
#23
